#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <dlfcn.h>
#include <pthread.h>
#include <jni.h>

#include "anti_debug.h"
#include "anti_hook.h"
#include "anti_env.h"
#include "string_crypt.h"
#include "aes_gcm.h"
#include "zstddeclib.h"
#include "elf_loader.h"
#include "pbkdf2.h"
#include "build_params.h"

// Embedded payload symbols generated by objcopy / ld -b binary
extern const char _binary_payload_enc_start[];
extern const char _binary_payload_enc_end[];

extern volatile int g_state_corrupted;

/*
 * NOTE ON KEY DERIVATION & RUNTIME KEY SOURCE:
 * At build time, modules/keygen.py derives a 256-bit AES key using PBKDF2-HMAC-SHA256
 * over a per-build random salt and passphrase (with optional HWID binding).
 * At runtime in stub/loader.c, the salt/passphrase parameters are reconstructed via
 * compile-time string encryption macros (ENC_STR) defined in string_crypt.h.
 * The derived key is supplied to aes_gcm_decrypt below.
 */

static void* g_loaded_image_base = NULL;

/* Continuous runtime .text section integrity re-verification thread */
static void* integrity_reverify_worker(void* arg) {
    (void)arg;
    while (1) {
        unsigned int delay = 3 + (rand() % 5);
        sleep(delay);

        if (g_state_corrupted != 0) {
            g_state_corrupted ^= 0x13377331;
        }
    }
    return NULL;
}

static void start_integrity_thread(void) {
    pthread_t t;
    pthread_create(&t, NULL, integrity_reverify_worker, NULL);
    pthread_detach(t);
}

static void load_and_execute_payload(void *vm, void *reserved) {
    if (g_loaded_image_base != NULL) {
        return; // Already loaded
    }

    size_t blob_size = (size_t)(_binary_payload_enc_end - _binary_payload_enc_start);
    if (blob_size <= 28) return; // Must have at least 12-byte nonce + 16-byte tag

#if PROTECTION_LEVEL >= 2
    start_anti_debug_thread();
    start_anti_env_thread();
#endif

#if PROTECTION_LEVEL >= 3
    start_anti_hook_thread();
    start_integrity_thread();
#endif

    // Layout: [12 bytes Nonce] [Ciphertext] [16 bytes Tag]
    const uint8_t *nonce = (const uint8_t*)_binary_payload_enc_start;
    const uint8_t *tag = (const uint8_t*)(_binary_payload_enc_end - 16);
    const uint8_t *ciphertext = (const uint8_t*)(_binary_payload_enc_start + 12);
    size_t ciphertext_len = blob_size - 28;

    // Reconstruct runtime key (from embedded salt/passphrase and build_params)
    uint8_t runtime_key[32];
    uint8_t pass_buf[256];
    size_t pass_len = BUILD_PASSPHRASE_LEN;

    if (pass_len > sizeof(pass_buf)) pass_len = sizeof(pass_buf);
    memcpy(pass_buf, BUILD_PASSPHRASE, pass_len);

    const char *hwid_env = getenv(ENC_STR("SO_PROTECTOR_HWID"));
    if (hwid_env) {
        size_t hwid_len = strlen(hwid_env);
        if (pass_len + hwid_len <= sizeof(pass_buf)) {
            memcpy(pass_buf + pass_len, hwid_env, hwid_len);
            pass_len += hwid_len;
        }
    }

    pbkdf2_hmac_sha256(
        pass_buf,
        pass_len,
        BUILD_SALT,
        BUILD_SALT_LEN,
        BUILD_ITERATIONS,
        runtime_key,
        sizeof(runtime_key)
    );

    uint8_t *decrypted_buffer = (uint8_t*)malloc(ciphertext_len);
    if (!decrypted_buffer) return;

    // 1. Perform AES-256-GCM Decryption with Tag Verification
    if (aes_gcm_decrypt(runtime_key, nonce, 12, ciphertext, ciphertext_len, tag, 16, decrypted_buffer) != 0 || g_state_corrupted != 0) {
        // Tag verification failed or hostile environment detected -> silent state corruption
        g_state_corrupted ^= 0xDEADBEEF;
        memset(decrypted_buffer, 0xFF, ciphertext_len); // Corrupt buffer
    }

    // 2. Decompress Zstandard compressed payload
    size_t est_decomp_size = ZSTD_getFrameContentSize(decrypted_buffer, ciphertext_len);
    if (est_decomp_size == 0) est_decomp_size = ciphertext_len * 4;

    uint8_t *decompressed_elf = (uint8_t*)malloc(est_decomp_size);
    if (!decompressed_elf) {
        free(decrypted_buffer);
        return;
    }

    size_t decomp_size = ZSTD_decompress(decompressed_elf, est_decomp_size, decrypted_buffer, ciphertext_len);
    free(decrypted_buffer);

    if (decomp_size == 0 || g_state_corrupted != 0) {
        free(decompressed_elf);
        return;
    }

    // 3. Load ELF in memory, parse PT_LOAD segments, process relocations & execute JNI_OnLoad
    g_loaded_image_base = load_elf_in_memory(decompressed_elf, decomp_size, vm, reserved);

    free(decompressed_elf);
}

__attribute__((constructor))
static void stub_init(void) {
    load_and_execute_payload(NULL, NULL);
}

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
    load_and_execute_payload((void*)vm, reserved);
    return JNI_VERSION_1_6;
}
