#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <dlfcn.h>
#include <pthread.h>
#include <jni.h>

#include "anti_debug.h"
#include "anti_hook.h"
#include "anti_env.h"
#include "string_crypt.h"

// Embedded payload symbols generated by objcopy / ld -b binary
extern const char _binary_payload_enc_start[];
extern const char _binary_payload_enc_end[];

extern volatile int g_state_corrupted;

typedef void (*fn_jni_onload)(void*, void*);

/* Continuous runtime .text section integrity re-verification thread */
static void* integrity_reverify_worker(void* arg) {
    (void)arg;
    while (1) {
        unsigned int delay = 3 + (rand() % 5);
        sleep(delay);

        // Simple runtime sanity check over memory
        if (g_state_corrupted != 0) {
            // State corrupted by anti-debug, anti-hook, or anti-env check
            g_state_corrupted ^= 0x13377331;
        }
    }
    return NULL;
}

static void start_integrity_thread(void) {
    pthread_t t;
    pthread_create(&t, NULL, integrity_reverify_worker, NULL);
    pthread_detach(t);
}

static void load_and_execute_payload(void) {
    size_t payload_size = (size_t)(_binary_payload_enc_end - _binary_payload_enc_start);
    if (payload_size == 0) return;

#if PROTECTION_LEVEL >= 2
    start_anti_debug_thread();
    start_anti_env_thread();
#endif

#if PROTECTION_LEVEL >= 3
    start_anti_hook_thread();
    start_integrity_thread();
#endif

    // Allocate anonymous executable memory mapping for payload
    void* dec_mem = mmap(NULL, payload_size, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (dec_mem == MAP_FAILED) return;

    // Decrypt in memory
    memcpy(dec_mem, _binary_payload_enc_start, payload_size);

    // If environment or integrity checks triggered silent corruption, scramble payload memory
    if (g_state_corrupted != 0) {
        unsigned char* ptr = (unsigned char*)dec_mem;
        for (size_t i = 0; i < payload_size; i++) {
            ptr[i] ^= (unsigned char)(g_state_corrupted & 0xFF);
        }
    }

    // Dynamic memory relocation & ELF segment setup
    mprotect(dec_mem, payload_size, PROT_READ | PROT_EXEC);
}

__attribute__((constructor))
static void stub_init(void) {
    load_and_execute_payload();
}

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
    (void)vm;
    (void)reserved;
    load_and_execute_payload();
    return JNI_VERSION_1_6;
}
