#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <dlfcn.h>
#include <jni.h>

#include "anti_debug.h"
#include "anti_hook.h"
#include "string_crypt.h"

// Embedded payload symbols generated by objcopy / ld -b binary
extern const char _binary_payload_enc_start[];
extern const char _binary_payload_enc_end[];

typedef void (*fn_jni_onload)(void*, void*);

static void load_and_execute_payload(void) {
    size_t payload_size = (size_t)(_binary_payload_enc_end - _binary_payload_enc_start);
    if (payload_size == 0) return;

#if PROTECTION_LEVEL >= 2
    start_anti_debug_thread();
#endif

#if PROTECTION_LEVEL >= 3
    start_anti_hook_thread();
#endif

    // Allocate anonymous executable memory mapping for payload
    void* dec_mem = mmap(NULL, payload_size, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (dec_mem == MAP_FAILED) return;

    // Decrypt in memory (AES-GCM / XOR stub)
    memcpy(dec_mem, _binary_payload_enc_start, payload_size);

    // Dynamic memory relocation & ELF segment setup stub
    mprotect(dec_mem, payload_size, PROT_READ | PROT_EXEC);
}

__attribute__((constructor))
static void stub_init(void) {
    load_and_execute_payload();
}

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
    (void)vm;
    (void)reserved;
    load_and_execute_payload();
    return JNI_VERSION_1_6;
}
